nomadslaravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('home');
Route::get('/detail/{slug}','DetailController@index')->name('detail');

//Route::post('/checkout/{id}','CheckoutController@process')
//    ->name('checkout_process')
//    ->middleware(['auth','verified']);

//Route::post('/checkouts/{id}','CheckoutController@process')
//    ->name('checkout_process')
//    ->middleware(['auth','verified']);

Route::post('/checkout-proses/{id}', 'CheckoutController@process')
    ->name('checkout-proses')
    ->middleware(['auth','verified']);

Route::get('/checkout/{id}','CheckoutController@index')
    ->name('checkout')
    ->middleware(['auth','verified']);



Route::post('/checkout/create/{detail_id}','CheckoutController@create')
    ->name('checkout-create')
    ->middleware(['auth','verified']);

Route::get('/checkout/remove/{detail_id}','CheckoutController@remove')
    ->name('checkout-remove')
    ->middleware(['auth','verified']);

Route::get('/checkout/confirm/{id}','CheckoutController@success')
    ->name('checkout-success')
    ->middleware(['auth','verified']);


Route::prefix('admin')
->namespace('Admin')
->middleware(['auth','admin'])
->group(function() {

    Route::get('/','DashboardController@index')
    ->name('dashboard');

    Route::resource('travel-package','TravelPackageController');
    Route::resource('gallery','GalleryController');
    Route::resource('transaction','TransactionController');


});


Auth::routes(['verify'=> true]);

nomadslaravel/app/Travelpackage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class  Travelpackage extends Model
{

    use SoftDeletes;
    protected $table = 'travel_packages';
    protected $fillable =[

        'title','slug','location','about','featured_event','language','foods',
        'departure_date','duration','type',
        'price'

    ];

    protected $hidden = [

            //

    ];

    public function galleries() {

        return $this->hasMany(Gallery::class,'travel_packages_id','id');

    }

}

nomadslaravel/app/Http/Controllers/Admin/TravelPackageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\TravelpackageRequest;
use App\TravelPackage;
use Illuminate\Http\Request;
use Illuminate\Support\str;


class TravelPackageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = TravelPackage::all();

        return view('pages.admin.travel-package.index',[

            'items'=>$items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
            return view('pages.admin.travel-package.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TravelpackageRequest $request)
    {
        $data= $request->all();
        $data['slug'] = str::slug($request->title);

        Travelpackage::create($data);
        return redirect()->route('travel-package.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Travelpackage::findorFail($id);

        return view('pages.admin.travel-package.edit',[

            'item'=>$item
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Travelpackagerequest $request, $id)
    {
        $data= $request->all();
        $data['slug'] = str::slug($request->title);

        $item = Travelpackage::findorFail($id);
        $item->update($data);

        return redirect()->route('travel-package.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = travelpackage::findorFail($id);
        $item->delete();
        return redirect()->route('travel-package.index');
    }
}

nomadslaravel/resources/views/pages/admin/travel-package/create.blade.php
@extends('layouts.admin')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800"> Tambah  Paket Travel</h1>  
    </div>

        @if ($errors->any())

        <div class="alert alert-danger">

            <ul>

                @foreach ($errors->all() as $error)
            <li>{{$error}}</li>
                @endforeach

            </ul>

        </div>
            
        @endif

        <div class="card-shadow">
            <div class="card-body">
            <form action="{{route('travel-package.store')}}" method="post">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title"
            placeholder="Title" value="{{old('title') }}">
            </div>

            <div class="form-group">
                <label for="Location">Location</label>
                <input type="text" class="form-control" name="location"
            placeholder="Location" value="{{old('location') }}">
            </div>
                <div class="form-group">
                    <label for="about">About</label>
                <textarea name="about" rows="10" class="d-block w-100 form-control">{{old('about')}}</textarea>
                </div>
                <div class="form-group">
                    <label for="featured_ Event">Featured event</label>
                    <input type="text" class="form-control" name="featured_event"
                placeholder="featured Event" value="{{old('featured_event') }}">
                </div>
                <div class="form-group">
                    <label for="Language">Language</label>
                    <input type="text" class="form-control" name="language"
                placeholder="language" value="{{old('language') }}">
                </div>
                <div class="form-group">
                    <label for="foods">foods</label>
                    <input type="text" class="form-control" name="foods"
                placeholder="foods" value="{{old('foods') }}">
                </div>
                <div class="form-group">
                    <label for="departure_date">Departure Date</label>
                    <input type="date" class="form-control" name="departure_date"
                placeholder="departure date" value="{{old('departure_date') }}">
                </div>
                <div class="form-group">
                    <label for="duration">Duration</label>
                    <input type="text" class="form-control" name="duration"
                placeholder="duration" value="{{old('duration') }}">
                </div>
                <div class="form-group">
                    <label for="type">Type</label>
                    <input type="text" class="form-control" name="type"
                placeholder="type" value="{{old('type') }}">
                </div>
                <div class="form-group">
                    <label for="departure_date">Price</label>
                    <input type="number" class="form-control" name="price"
                placeholder="price" value="{{old('price') }}">
                </div>
                <button type="submit" class="btn btn-primary btn-block">
                    Simpan
                </button>
            </form>
            </div>
        </div>

  </div>
  <!-- /.container-fluid -->


@endsection

nomadslaravel/resources/views/pages/admin/travel-package/edit.blade.php
@extends('layouts.admin')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"> Edit  Paket Travel{{ $item->title  }}</h1>  
    </div>

        @if ($errors->any())

        <div class="alert alert-danger">

            <ul>

                @foreach ($errors->all() as $error)
            <li>{{$error}}</li>
                @endforeach

            </ul>

        </div>
            
        @endif

        <div class="card-shadow">
            <div class="card-body">
            <form action="{{route('travel-package.update',$item->id)}}" method="post">
                @method('PUT')
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title"
            placeholder="Title" value="{{ $item->title }}">
            </div>

            <div class="form-group">
                <label for="Location">Location</label>
                <input type="text" class="form-control" name="location"
            placeholder="Location" value="{{$item->location }}">
            </div>
                <div class="form-group">
                    <label for="about">About</label>
                <textarea name="about" rows="10" class="d-block w-100 form-control">{{$item->about}}</textarea>
                </div>
                <div class="form-group">
                    <label for="featured_ Event">Featured event</label>
                    <input type="text" class="form-control" name="featured_event"
                placeholder="featured Event" value="{{$item->featured_event}}">
                </div>
                <div class="form-group">
                    <label for="Language">Language</label>
                    <input type="text" class="form-control" name="language"
                placeholder="language" value="{{$item->language}}">
                </div>
                <div class="form-group">
                    <label for="foods">foods</label>
                    <input type="text" class="form-control" name="foods"
                placeholder="foods" value="{{$item->foods}}">
                </div>
                <div class="form-group">
                    <label for="departure_date">Departure Date</label>
                    <input type="date" class="form-control" name="departure_date"
                placeholder="departure date" value="{{$item->departure_date }}">
                </div>
                <div class="form-group">
                    <label for="duration">Duration</label>
                    <input type="text" class="form-control" name="duration"
                placeholder="duration" value="{{$item->duration}}">
                </div>
                <div class="form-group">
                    <label for="type">Type</label>
                    <input type="text" class="form-control" name="type"
                placeholder="type" value="{{$item->type }}">
                </div>
                <div class="form-group">
                    <label for="departure_date">Price</label>
                    <input type="number" class="form-control" name="price"
                placeholder="price" value="{{$item->price}}">
                </div>
                <button type="submit" class="btn btn-primary btn-block">
                    Ubah
                </button>
            </form>
            </div>
        </div>

  </div>
  <!-- /.container-fluid -->


@endsection

nomadslaravel/resources/views/pages/admin/travel-package/index.blade.php
@extends('layouts.admin')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h1 class="h3 mb-0 text-gray-800">Paket Travel</h1>  
    <a href="{{route('travel-package.create') }}" class="btn btn-sm btn-primary shadow-sm">
    <i class="fas fa-plus fa-sm text-white-50"></i>
    Tambah Paket Travel
    </a>
    </div>

    <div class="row">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">

                    <thead>

                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Location</th>
                            <th>Type</th>
                            <th>Departure Date</th>
                            <th>Type</th>
                            <th>Action</th>

                        </tr>

                    </thead>

                    <tbody>

                        @forelse ($items as $item)
                        <tr>
                        <td>{{$item->id }}</td>
                        <td>{{$item->title }}</td>
                        <td>{{$item->location }}</td>
                        <td>{{$item->type }}</td>
                        <td>{{$item->departure_date }}</td>
                        <td>{{$item->type}}</td>

                            <td>
                            <a href="{{ route('travel-package.edit',$item->id) }}" class="btn btn-info">
                                <i class="fa fa-pencil-alt"></i>
                            </a>    
                        <form action="{{ route('travel-package.destroy',$item->id)}}" method="POST"
                            class=d-inline>
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                            </td>
                        </tr>
    
                        @empty

                        <tr>

                            <td colspan="7" class="text-center">
                                Data Kosong
                            </td>
                        </tr>
                            
                        @endforelse
                       
                    </tbody>

                </table>
            </div>

        </div>

    </div>
  </div>
  <!-- /.container-fluid -->


@endsection